site: "Prudent Mariners :: A Mobile Marine Services Company"

title: "Prudent Mariners :: A Mobile Marine Services Company"
email: "info@prudentmariners.com"
description: > # this means to ignore newlines until "baseurl:"
              "We are the premiere full service mobile marine company on the
              Chesapeake Bay, serving Virginia, Maryland, Delaware and North Eastern North Carolina,
              specializing in cruising yacht maintenance, repair and delivery."

#gh-pages
url: https://www.prudentmariners.com
enforce_ssl: www.prudentmariners.com
repository: prudentmariners.github.io
baseurl: ""

twitter_username: prudentmariners
instagram_username: prudentmariners
facebook_username: prudentmariners
youtube_username: UCEciWv63Kez_M72GE_VnReQ
phone: "757-453-3092"

google_analytics: UA-129009825-1

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"
