# Site settings
title: "Prudent Mariners :: A Marine Services Company"
email: "info@prudentmariners.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.prudentmariners.com" # the base hostname & protocol for your site

twitter_username: prudentmariners
instagram_username: prudentmariners
facebook_username: prudentmariners
youtube_username: UCEciWv63Kez_M72GE_VnReQ
phone: "757-453-3092"

google_analytics: UA-129009825-1

# Build settings
markdown: kramdown

#gh-pages
url: https://www.prudentmariners.com
enforce_ssl: www.prudentmariners.com
